# Chevron Glance

"$schema" = 'https://starship.rs/config-schema.json'

#right_format = """$all"""

format = """
[](fg:sec)\
$sudo\
$os\
$jobs\
$username\
$hostname\
$localip\
$git_status\
$directory\
$git_commit$git_state$git_metrics\
$git_branch\
$memory_usage\
$status\
[ ](fg:prim)\
$cmd_duration\
$line_break$character
"""


add_newline = false

palette = "chevron_glance"

[palettes.chevron_glance]
prim = '#a7906f' #Primary/Directory Background
sec = '#3a3a3a' #Accents
primt = '#3a3a3a' #Primary text color (non-glyphic)
sudo = '#9c454e'
user = '#274693'
host = '#FCA17D'
ip = '#FCA17D'
duration = '#8a8a8a'
# Git Colors
tert = '#3a3a3a' #Tertiary color, mostly used for GitHub text.
conflicted = 'red'
ahead = 'cyan'
behind = 'orange'
diverged = 'blue'
uptodate = 'green'
untracked = 'purple'
stashed =  '#6b84eb' #light blue
modified = 'yellow'
staged = '#c5e187' #sage
renamed = '#ce63ff' #lilac
deleted = '#f54caf' #pink

[sudo]
format = '[ ]($style)'
style = 'fg:sudo bg:sec'
disabled = true

[os]
format = "[$symbol ]($style)"
style = "fg:prim bg:sec"
disabled = false

[os.symbols]
Alpine = ""
Amazon = ""
Android = ""
Arch = ""
CentOS = ""
Debian = ""
DragonFly = "🐉" # ""
Emscripten = "🔗"
EndeavourOS = "" # ""
Fedora = ""
FreeBSD = ""
Garuda = ""
Gentoo = ""
HardenedBSD = "聯"
Illumos = "🐦"
Linux = ""
Macos = ""
Manjaro = ""
Mariner = ""
MidnightBSD = "🌘"
Mint = ""
NetBSD = ""
NixOS = ""
OpenBSD = "" # ""
OpenCloudOS = "☁️"
openEuler = ""
openSUSE = ""
OracleLinux = "⊂⊃"
Pop = "" # ""
Raspbian = ""
Redhat = ""
RedHatEnterprise = ""
Redox = "🧪"
Solus = "" # " "
SUSE = ""
Ubuntu = ""
Unknown = ""
Windows = ""

[jobs]
format = '[]($style)[$symbol$number](fg:primt bg:prim)[]($style)'
style = 'fg:prim bg:sec'
symbol = '󰇺 '
symbol_threshold = 1
number_threshold = 2
disabled = false

[username]
format = '[](fg:sec bg:user)[ $user ]($style)[](fg:user bg:sec)'
style_user = 'fg:#FFFFFF bg:user'
style_root = 'fg:#FFFFFF bold bg:sudo'
show_always = true
disabled = false

[hostname]
format = '[ ](bg:sec)[@](fg:prim bold bg:sec)[ ](bg:sec)[](fg:sec bg:host)[$ssh_symbol](fg:primt bold bg:host)[ $hostname ](fg:primt bold bg:host)[](fg:host bg:sec)'
ssh_only = true
ssh_symbol = ' '
#trim_at = '.companyname.com'
disabled = false

[localip]
format = '[](fg:sec bg:ip)[ $localipv4 ](fg:primt bold bg:ip)[](fg:ip bg:sec)'
ssh_only = true
disabled = false

[git_status]
format = '([$all_status$ahead_behind]($style))[](fg:sec bg:prim)'
style = 'fg:prim bg:tert'
conflicted = '[](fg:sec bg:conflicted)[](fg:conflicted bg:sec)'
ahead = '[](fg:sec bg:ahead)[](fg:ahead bg:sec)'
behind = '[](fg:sec bg:behind)[](fg:behind bg:behind)'
diverged = '[](fg:sec bg:ahead)[](fg:ahead bg:sec)'
up_to_date = '[](fg:sec bg:uptodate)[](fg:uptodate bg:sec)'
untracked = '[](fg:sec bg:untracked)[](fg:untracked bg:sec)'
stashed = '[](fg:sec bg:stashed)[](fg:stashed bg:sec)'
modified = '[](fg:sec bg:modified)[](fg:modified bg:sec)'
staged = '[](fg:sec bg:staged)[](fg:staged bg:sec)'
renamed = '[](fg:sec bg:renamed)[](fg:renamed bg:sec)'
deleted = '[](fg:sec bg:deleted)[](fg:deleted bg:sec)'
disabled = false

[directory]
format = '[ ]($style)[$read_only](fg:primt bg:prim)[$repo_root]($repo_root_style)[$path](fg:primt bold bg:prim)'
style = 'fg:sec bg:prim'
home_symbol = ' ~'
read_only = '󰉐 '
#read_only_style = 'fg: bg:'
truncation_length = 2
truncation_symbol = '…/'
truncate_to_repo = true
repo_root_format = '[  ](fg:sec bg:prim)[$read_only]($read_only_style)[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[ ](bg:prim)'
repo_root_style	= 'fg:sec bold bg:prim'
use_os_path_sep = true
disabled = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
".config" = ". "
".dotfiles" = ". "

[git_branch]
format = '[](fg:tert bg:prim)[$symbol $branch(:$remote_branch)]($style)[](fg:tert bg:prim)'
style = 'fg:prim bold bg:tert'
symbol = ''

[memory_usage]
format = '[](fg:prim bg:sec)[$symbol]($style)[](fg:sec bg:prim)'
style = 'fg:sudo bg:sec'
symbol = '  !'
threshold = 75
disabled = false

[status]
format = '[$symbol]($style)'
style = 'fg:sudo bg:prim'
symbol = '  '
disabled = false

[cmd_duration]
format = '[󰾨 $duration ]($style)'
style = 'fg:duration'
min_time = 500
disabled = false

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[ 󱞩](bold fg:prim)'
error_symbol = '[ 󱞩](bold fg:sudo)'
vimcmd_symbol = '[ ](bold fg:prim)'
vimcmd_replace_one_symbol = '[ ](bold fg:purple)'
vimcmd_replace_symbol = '[ ](bold fg:purple)'
vimcmd_visual_symbol = '[ ](bold fg:yellow)'

