#!/usr/bin/env ruby
#
# Homebrew Bundle file
# - https://github.com/Homebrew/homebrew-bundle
#

## Shells

# Bash
# brew 'bash'
# brew 'bash-completion@2'

# Zsh
# brew 'zsh'
# brew 'zsh-autosuggestions'
# brew 'zsh-completions'
# brew 'zsh-history-substring-search'
# brew 'zsh-syntax-highlighting'

# pre-req
# stow git make zsh

## Taps
tap "buo/cask-upgrade"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"


#
# Local Brewfile's
#

Dir.glob(File.expand_path('~/.config/homebrew/Brewfile.*')).each do |file|
  next if file.end_with?('.lock.json')
  instance_eval File.read(file) if File.exists?(file)
end

#
# Only macOS beyond here
#

require 'os'
return unless OS.mac?

## Packages

brew "ack"
brew "bat"
brew "cheat"
brew "coreutils"
brew "ctop"
brew "git-delta"
brew "diff-so-fancy"
brew "difftastic"
brew "direnv"
brew "dog"
brew "duf"
brew "dust"
brew "exa"
brew "fd"
brew "fzf"
brew "gh"
brew "git"
brew "git-extras"
brew "gping"
brew "helix"
brew "htop"
brew "hub"
brew "jq"
brew "m-cli"
brew "mas"
brew "neovim"
brew "prettyping"
brew "procs"
brew "ripgrep"
brew "starship"
brew "stow"
brew "thefuck"
brew "tig"
brew "tldr"
brew "trash"
brew "tree"
brew "wget"
brew "yq"
brew "zoxide"
brew "zsh"

## Fonts
cask "font-hack-nerd-font"
cask "font-jetbrains-mono-nerd-font"

## Casks
cask "1password"
cask "1password-cli"
cask "appcleaner"
cask "barrier"
cask "bartender"
cask "betterdisplay"
cask "bettermouse"
cask "cakebrew"
cask "dash"
cask "discord"
cask "fantastical"
cask "fmail2"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "hazel"
cask "home-assistant"
cask "keka"
cask "little-snitch"
cask "notion"
cask "prefs-editor"
cask "prusaslicer"
cask "sourcetree"
cask "qlcolorcode", args: { appdir: "/Applications" }
cask "qlimagesize", args: { appdir: "/Applications" }
cask "qlmarkdown", args: { appdir: "/Applications" }
cask "qlstephen", args: { appdir: "/Applications" }
cask "quicklook-csv", args: { appdir: "/Applications" }
cask "quicklook-json", args: { appdir: "/Applications" }
cask "sonos"
cask "spotify"
cask "suspicious-package"
cask "todoist"
cask "utm"
cask "visual-studio-code"
cask "warp"
cask "zoom"


## Mac App Store
mas "1Password for Safari", id: 1569813296
mas "Airmail", id: 918858936
mas "Amphetamine", id: 937984704
mas "Magnet", id: 441258766
mas "Menu Bar Controller for Sonos", id: 1357379892
mas "Microsoft Remote Desktop", id: 1295203466
mas "Reeder", id: 1529448980
mas "Screens", id: 1224268771






